name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: 'master'
      - name: Install SSH key
        uses: rezaiyan/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - run: |
          git remote add container https://github.com/rezaiyan/rezaiyan-hugo.git
          git config --global user.email "alirezaiyann@gmial.com"
          git config --global user.name "rezaiyan"
          git checkout master
          git push -u container master